name: Deploy CDK

on:
  push:
    branches: [main]
    paths:
      - "infrastructure/**"
      - "workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install Dependencies
        working-directory: infrastructure
        run: npm ci

      - name: Build CDK Project
        working-directory: infrastructure
        run: npm run build

      - name: Test CDK Project
        working-directory: infrastructure
        run: npm run test

      - name: Deploy CDK
        working-directory: infrastructure
        run: npx cdk deploy
