name: Build CDK

on:
  push:
    branches: [ main ]
    paths:
      - 'infrastructure/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'infrastructure/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - name: Build CDK Project and synth cloud formation
        working-directory: infrastructure
        run: npm ci
        run: npm run build
        run: npm run test
        run: npx cdk synth
