name: Build API

on:
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Build
        working-directory: api
        run: docker build .
