name: Build API

on:
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/test-verify-api.yml"

jobs:
  set-matrix:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}

    steps:
      - uses: actions/checkout@v2

      - id: set-matrix
        uses: ./.github/actions/get-matrix
        with:
          file-path: ./routes.json

  build:
    needs: [set-matrix]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: echo "${{ needs.set-matrix.outputs.matrix }}"

      - name: Run Docker Build
        env:
          ENDPOINT: ${{ matrix.path }}
        working-directory: api
        run: docker build --build-arg endpoint=$ENDPOINT .
