name: Build CDK

on:
  pull_request:
    branches: [main]
    paths:
      - "infrastructure/**"
      - ".github/workflows/test-verify-infrastructure.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: infrastructure

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "15"

      - name: Install Dependencies
        run: npm ci

      - name: Build CDK Project
        run: npm run build

      - name: Test CDK Project
        run: npm run test

      - name: Synth cloud formation
        run: npx cdk synth
