name: Build API

on:
  pull_request:
    branches: [main]
    paths:
      - "api/**"
      - ".github/workflows/test-verify-api.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        endpoint: [users]

    steps:
      - uses: actions/checkout@v2

      - name: Run Docker Build
        env:
          ENDPOINT: ${{ matrix.endpoint }}
        working-directory: api
        run: docker build --build-arg endpoint=$ENDPOINT .
